project:
  type: website

website:
  title: "A clumpsy data analyst blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Alex-Nguyen-VN
format:
  html:
    theme: cosmo
    css: styles.css



